# config for hypridle

# basic cmds to run
general {
    lock_cmd = pidof hyprlock || hyprlock		# use hyprlock as the lock screen (avoids starting multiple instances)
    before_sleep_cmd = loginctl lock-session                                  # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# lock screen after 15 mins
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# turn off screen after 30 mins
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

# suspend pc after 60 mins
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
